version: '3.3'
services:
    mysql:
        image: mysql:8.0
        container_name: app_mysql
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./var/lib/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        command: --default-authentication-plugin=mysql_native_password
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: app_phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql
