version: '3.3'
services:
    mysql:
        image: mysql:5.7
        container_name: app_mysql
        ports:
            - 3306:3306
        volumes:
            - ./var/lib/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: app_phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql
